### PR TITLE
Make better button docs

### PR DESCRIPTION
**Pull request by frehner**
https://shopify-dev.shopify-dev-minimal-pfjv.anthony-frehner.us.spin.dev/api/hydrogen-react/components/addtocartbutton

### CODE REVIEW

**Review by johndcollett — APPROVED** [review]
Changes look great to me.

**Review by abharvey — APPROVED** [review]

**Comment by johndcollett** [comment]
@wizardlyhel 

The ShopPayButton is one where I think the current complex type does a better job of describing the either or that is actually happening than an interface can.

The current docs: https://shopify.dev/api/hydrogen/components/primitive/shoppaybutton#props, at a glance make it seem like you can use both a prop called variantIds and variantIdsAndQuantities. The text above does describes the actual situation but as a developer I think the typescript does it more elegantly.

Thoughts?

**Comment by wizardlyhel** [comment]
👍

**Comment by frehner** [comment]
Thanks all!

**Pull request merged**
